logging:
  level:
    root: debug
    sun: error
    javax: error
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%level][%logger{1000}][%method][%L] - %msg%n"

spring:
  datasource:
    sdcuike:
      url: jdbc:mysql://localhost:3306/sample_db
      password: rootroot
      username: root
      filters: stat,demo3Filter


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    default-fetch-size: 100
  type-aliases-package: com.sdcuike.springboot.domain
